version: '3'

services:
  webapi:
    build: .
    restart: unless-stopped
    command: bash -c "python manage.py runserver 0.0.0.0:8001"
    env_file:
      - ./env/dev.env
    volumes:
      - .:/web_api
    ports:
      - "8001:8001"
    entrypoint: /entrypoint.sh

